#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-pry-doc
Version  : 0.8.0
Release  : 5
URL      : https://rubygems.org/downloads/pry-doc-0.8.0.gem
Source0  : https://rubygems.org/downloads/pry-doc-0.8.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-pry-doc-lib
BuildRequires : ruby
BuildRequires : rubygem-bacon
BuildRequires : rubygem-coderay
BuildRequires : rubygem-method_source
BuildRequires : rubygem-pry
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-slop
BuildRequires : rubygem-yard

%description
![Pry Doc][logo]
* Repository: [https://github.com/pry/pry-doc][repo]
* Wiki: [https://github.com/pry/pry-doc/wiki][wiki]
* [![Build Status](https://travis-ci.org/pry/pry-doc.svg?branch=master)](https://travis-ci.org/pry/pry-doc)

%package lib
Summary: lib components for the rubygem-pry-doc package.
Group: Libraries

%description lib
lib components for the rubygem-pry-doc package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n pry-doc-0.8.0
gem spec %{SOURCE0} -l --ruby > rubygem-pry-doc.gemspec

%build
gem build rubygem-pry-doc.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
pry-doc-0.8.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/pry-doc-0.8.0
rspec spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/pry-doc-0.8.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/aliases-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/c_files_found%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/cache-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/cached%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/cdesc-MethodInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/find_gem_dir-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/gem_dir_from_method-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/gem_root-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/guess_gem_name_from_module_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/info_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/is_eval_method%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/is_singleton%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/method_host-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/parse_and_cache_if_gem_cext-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/receiver_notation_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/MethodInfo/registry_lookup-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/Pry/cdesc-Pry.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/PryDoc/cdesc-PryDoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/PryDoc/load_yardoc-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/lib/pry-doc/core_docs_19/page-checksums.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/lib/pry-doc/core_docs_20/page-checksums.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/lib/pry-doc/core_docs_21/page-checksums.ri
/usr/lib64/ruby/gems/2.2.0/doc/pry-doc-0.8.0/ri/lib/pry-doc/core_docs_22/page-checksums.ri
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc.rb
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_19/checksums
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_19/object_types
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_19/objects/root.dat
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_19/proxy_types
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_20/checksums
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_20/object_types
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_20/objects/root.dat
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_20/proxy_types
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_21/checksums
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_21/object_types
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_21/objects/root.dat
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_21/proxy_types
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_22/checksums
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_22/object_types
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_22/objects/root.dat
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_22/proxy_types
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/lib/pry-doc/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/pry-doc.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/ext/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/ext/extconf.rb
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/ext/sample.c
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/ext/sample.o
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/lib/sample.rb
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/sample.rb
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/spec/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/spec/pry-doc_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/pry-doc-0.8.0.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/ext/sample.so
