#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-pry-doc
Version  : 0.8.0
Release  : 7
URL      : https://rubygems.org/downloads/pry-doc-0.8.0.gem
Source0  : https://rubygems.org/downloads/pry-doc-0.8.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-pry
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
![Pry Doc][logo]
* Repository: [https://github.com/pry/pry-doc][repo]
* Wiki: [https://github.com/pry/pry-doc/wiki][wiki]
* [![Build Status](https://travis-ci.org/pry/pry-doc.svg?branch=master)](https://travis-ci.org/pry/pry-doc)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n pry-doc-0.8.0
gem spec %{SOURCE0} -l --ruby > rubygem-pry-doc.gemspec

%build
gem build rubygem-pry-doc.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
pry-doc-0.8.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/pry-doc-0.8.0
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/pry-doc-0.8.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc.rb
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_19/checksums
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_19/object_types
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_19/objects/root.dat
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_19/proxy_types
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_20/checksums
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_20/object_types
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_20/objects/root.dat
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_20/proxy_types
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_21/checksums
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_21/object_types
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_21/objects/root.dat
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_21/proxy_types
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_22/checksums
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_22/object_types
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_22/objects/root.dat
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/core_docs_22/proxy_types
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/lib/pry-doc/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/pry-doc.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/ext/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/ext/sample.c
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/lib/sample.rb
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/spec/gem_with_cext/gems/sample.rb
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/spec/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/pry-doc-0.8.0/spec/pry-doc_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/pry-doc-0.8.0.gemspec
